version: '3'
services:
  app:
    build: .
    ports:
      - "4001:4001"
    command: yarn startTestServer
    environment:
      - RUNNING_JEST=true
    depends_on:
      - dgraph-alpha
  test-api:
    build: .
    command: yarn test
    depends_on:
      - app
    environment:
      - RUNNING_JEST=true
  dgraph-zero:
    image: dgraph/dgraph:latest
    ports:
      - "5080:5080"
    command: dgraph zero --my dgraph-zero:5080

  dgraph-alpha:
    image: dgraph/dgraph:latest
    ports:
      - "8080:8080"
      - "9080:9080"
    command: dgraph alpha --my dgraph-alpha:7080 --zero dgraph-zero:5080 --security "whitelist=0.0.0.0/0"
    depends_on:
      - dgraph-zero
